# Generated by Django 4.0.5 on 2022-06-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_reciperequirements_reciperequirement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchases',
            new_name='Purchase',
        ),
    ]
